name: deploy

on:
  push:
  pull_request:
  release:

jobs:
  document-and-deploy:
    # Skip deploy for automated (e.g., documentation) and [no-deploy] commits
    if: "!contains(github.event.head_commit.message, '[automated]') && !contains(github.event.head_commit.message, '[no-deploy]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Set up R version
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "oldrel" # As shinyapps.io needs some time to catch up after releases
          use-public-rspm: true

      - name: Deploy to Shiny
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          R -e "
            install.packages('rsconnect');
            rsconnect::setAccountInfo(name='forrt', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}});
            rsconnect::deployApp(appName = 'os-mapping',  forceUpdate = TRUE);
          "
